### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rafraph**
Adding some more info about ration and quality so users can understand better how to use it

### CODE REVIEW

**Comment by dfa1234** [comment]
Great, thank a lot for the relevant info @rafraph

**Comment by rafraph** [comment]
Thank you David for this great package.
BTW, I think this sentence that I added is not accurate:
"ratio of 50 will decrease the resolution by 2. i.e. image of 2000 X 1500
pixels will become 1000 X 750 pixels"
It should be:
"ratio of 50 will decrease the resolution of each dimension by 2. i.e.
image of 2000 X 1500 pixels will become 1000 X 750 pixels"
Of course this will decrease the whole resolution by 4.
Rafael

‫בתאריך יום ג׳, 4 בינו׳ 2022 ב-17:27 מאת ‪David‬‏ ***@***.***
‬‏>:‬

**Comment by dfa1234** [comment]
תודה :)

**Comment by rafraph** [comment]
😉

‫בתאריך יום ה׳, 6 בינו׳ 2022 ב-12:03 מאת ‪David‬‏ ***@***.***
‬‏>:‬

**Pull request merged**
